#!/usr/bin/env node

var fs = require('fs');
var colors = require('colors');
var program = require('commander');
var sqljs = require('sqljs');
var handlebars = require('handlebars');
var inflection = require('inflection');
var _ = require('lodash');

var Entity = require('./classes/entity.js');


program
  .version('0.0.1')
  .option('-i, --input [input sql path]', 'Specify input SQL file')
  .option('-o, --output [output blueprint path]', 'Specify output Blueprint API file')
  .parse(process.argv);

var app = {

	init: function() {
		var sqlString = this.getSQLString();
		var entities = this.getEntitiesFromSQL(sqlString);

		this.generate(entities);
	},

	getSQLString: function() {
		var sql = fs.readFileSync(program.input).toString();

		//remove set params
		sql = sql.replace(/SET(.*?);/gmi, '');

		//DATETIMEs are freaking out sqljs?
		sql = sql.replace(new RegExp("DATETIME", "g"), 'INT');
		//DATEs are freaking out sqljs?
		sql = sql.replace(new RegExp("DATE", "g"), 'INT');
		//BITs are freaking out sqljs?
		sql = sql.replace(new RegExp("BIT", "g"), 'SMALLINT');

		return sql;
	},

	getEntitiesFromSQL: function(sql) {
		var entities = [];
		var sqlParseOptions = new sqljs.ParseOptions();
		var statements = sqljs.parse(sql, undefined, sqlParseOptions);
		console.log('[Found] '.green, statements.length + ' CREATE TABLE statements');

		//build entities collection
		statements.forEach(function(statement){
			if(statement.statement === 'CREATE' && statement.what === 'TABLE') {

				var fields = [];
				statement.definitions.forEach(function(definition){
					if(definition.name) {
						fields.push({
							name: definition.name,
							type: definition.type,
							notNull: definition.notNull,
						});
					}
				});

				var entity = new Entity(statement.table, fields);
				entities.push(entity);
			}
		});

		return entities;
	},

	//then https://github.com/apiaryio/matter_compiler
	createAST: function(entities) {
		var ast = {
			_version: '2.0',
			metadata: [
				{
					name: 'FORMAT',
					value: '1A'
				}
			],
			name: 'My API',
			description: 'Description of *My API*.\n\n',
			resourceGroups: []
		};

		var groups = [];

		entities.forEach(function(entity){
			groups.push(entity.getResourceGroup());
		});


		ast.resourceGroups = groups;
		fs.writeFile((program.output + '.json'), JSON.stringify(ast, null, 4));
	},

	runMatterCompiler: function() {
		var exec = require("child_process").exec;

		exec(('matter_compiler ' + program.output + '.json > ' + program.output), function (err, stdout, stderr) {
			console.log("[Done]".green);
		});
	},

	generate: function(entities) {
		this.createAST(entities);
		this.runMatterCompiler();
	}
};

//kickoff
app.init();